### ============================================
### Solana Blockchain API — Pruebas
### Usa la extensión "REST Client" para ejecutar
### Click en "Send Request" arriba de cada bloque
### ============================================

### 1. Estado del servidor
GET http://localhost:3000/

### 2. Listado de endpoints
GET http://localhost:3000/api

### 3. Health check de Solana
GET http://localhost:3000/wallet/health

### 4. Balance de wallet
GET http://localhost:3000/wallet/6jHGrsG1HAiV7DpWFtzPoAYnSp4fb4t53MSFc5ykjHxu/balance

### 5. Transacciones de wallet
GET http://localhost:3000/wallet/6jHGrsG1HAiV7DpWFtzPoAYnSp4fb4t53MSFc5ykjHxu/transactions

### 6. Transacciones con límite
GET http://localhost:3000/wallet/6jHGrsG1HAiV7DpWFtzPoAYnSp4fb4t53MSFc5ykjHxu/transactions?limit=5

### 7. Detalle de una transacción
GET http://localhost:3000/wallet/transaction/4aguv6rLQm3FTqR3RecYX8ovqXNQK3U5THUuwmkoMdWJR9pHtQSdgvz8trh5ngQhQcTLJApPjuuTBqzaLLySyjaU
